name: numba-xnd
channels:
  - numba
  - xnd/label/dev
  - conda-forge
dependencies:
  - python=3.7
  - llvmlite
  - numpy
  - gumath
  - xnd
  - coverage
  - codecov
  - pyyaml # for numba config parsing
  - ipython # for developing
  - numba
  - pytest
  - pytest-xdist
  - colorama
